name: flutter_mfw
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  badges: ^1.1.1
  flutter_spinkit: "^4.1.2"

  flutter_screenutil: ^0.5.3
  flutter_staggered_grid_view: ^0.3.0
  provider: ^2.0.1+1
  dio: ^2.1.13
  quantize_dart: ^1.0.1
  color_thief_flutter: ^1.0.0
  flutter_swiper: ^1.1.6
  cached_network_image: 0.8.0
  webview_flutter: ^0.3.5+2
  jhtoast: ^0.1.0
  azlistview: ^0.1.2  #latest version
  # 汉字转拼音库 https://github.com/flutterchina/lpinyin
  lpinyin: ^1.0.9
  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: ^1.2.1
  # 高德地图定位
  amap_location: ^0.2.0
  amap_map_fluttify: ^0.10.0
  amap_search_fluttify: ^0.4.0
  shared_preferences: ^0.4.2
  json_annotation: ^2.0.0
  font_awesome_flutter: any
  random_pk: any
  image_picker: ^0.6.0+9
  dio_cookie_manager: ^0.0.1
  fluwx: 0.5.0
  file_picker: ^1.3.8
  video_player: ^0.6.4
  flutter_calendar: ^0.0.1
  # simple_permissions: ^0.1.1
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  json_model: ^0.0.2 #最新版本

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

      - assets/images/icon_favourite.png
      - assets/images/2.0x/icon_favourite.png
      - assets/images/3.0x/icon_favourite.png

      - assets/images/icon_message.png
      - assets/images/2.0x/icon_message.png
      - assets/images/3.0x/icon_message.png

      - assets/images/icon_gonglve.png
      - assets/images/2.0x/icon_gonglve.png
      - assets/images/3.0x/icon_gonglve.png

      - assets/images/icon_hote.png
      - assets/images/2.0x/icon_hote.png
      - assets/images/3.0x/icon_hote.png

      - assets/images/icon_jipiao.png
      - assets/images/2.0x/icon_jipiao.png
      - assets/images/3.0x/icon_jipiao.png

      - assets/images/icon_travel.png
      - assets/images/2.0x/icon_travel.png
      - assets/images/3.0x/icon_travel.png

      - assets/images/icon_youji.png
      - assets/images/2.0x/icon_youji.png
      - assets/images/3.0x/icon_youji.png

      - assets/images/icon_huxian.png
      - assets/images/2.0x/icon_huxian.png
      - assets/images/3.0x/icon_huxian.png

      - assets/images/icon_fengye.png
      - assets/images/2.0x/icon_fengye.png
      - assets/images/3.0x/icon_fengye.png

      - assets/images/icon_right.png
      - assets/images/2.0x/icon_right.png
      - assets/images/3.0x/icon_right.png

      - assets/images/setting.png
      - assets/images/2.0x/setting.png
      - assets/images/3.0x/setting.png

      - assets/images/saoma.png
      - assets/images/2.0x/saoma.png
      - assets/images/3.0x/saoma.png

      - assets/images/start.png
      - assets/images/2.0x/start.png
      - assets/images/3.0x/start.png

      - assets/images/order.png
      - assets/images/2.0x/order.png
      - assets/images/3.0x/order.png

      - assets/images/lishi.png
      - assets/images/2.0x/lishi.png
      - assets/images/3.0x/lishi.png

      - assets/images/topic.png
      - assets/images/2.0x/topic.png
      - assets/images/3.0x/topic.png

      - assets/images/qianbi.png
      - assets/images/2.0x/qianbi.png
      - assets/images/3.0x/qianbi.png

      - assets/images/tab_default_mall.png
      - assets/images/2.0x/tab_default_mall.png
      - assets/images/3.0x/tab_default_mall.png

      - assets/images/tab_destination_normal.png
      - assets/images/2.0x/tab_destination_normal.png
      - assets/images/3.0x/tab_destination_normal.png

      - assets/images/tab_destination_selected.png
      - assets/images/2.0x/tab_destination_selected.png
      - assets/images/3.0x/tab_destination_selected.png

      - assets/images/tab_focused_mall.png
      - assets/images/2.0x/tab_focused_mall.png
      - assets/images/3.0x/tab_focused_mall.png

      - assets/images/tab_homepage_normal.png
      - assets/images/2.0x/tab_homepage_normal.png
      - assets/images/3.0x/tab_homepage_normal.png

      - assets/images/tab_homepage_refresh.png
      - assets/images/2.0x/tab_homepage_refresh.png
      - assets/images/3.0x/tab_homepage_refresh.png

      - assets/images/tab_homepage_selected.png
      - assets/images/2.0x/tab_homepage_selected.png
      - assets/images/3.0x/tab_homepage_selected.png

      - assets/images/tab_hotel_normal.png
      - assets/images/2.0x/tab_hotel_normal.png
      - assets/images/3.0x/tab_hotel_normal.png

      - assets/images/tab_hotel_selected.png
      - assets/images/2.0x/tab_hotel_selected.png
      - assets/images/3.0x/tab_hotel_selected.png

      - assets/images/tab_mine_normal.png
      - assets/images/2.0x/tab_mine_normal.png
      - assets/images/3.0x/tab_mine_normal.png

      - assets/images/tab_mine_selected.png
      - assets/images/2.0x/tab_mine_selected.png
      - assets/images/3.0x/tab_mine_selected.png

      - assets/tabicons/home.png
      - assets/tabicons/home_select.png
      - assets/tabicons/cloud.png
      - assets/tabicons/colud_select.png
      - assets/tabicons/goods.png
      - assets/tabicons/goods_select.png
      - assets/tabicons/my.png
      - assets/tabicons/my_selset.png

      - assets/headerbg1.jpg
      - assets/placehold1.png 
      - assets/topicheader.jpeg
      - assets/shares/conect.png
      - assets/shares/download.png
      - assets/shares/qqkojian.png
      - assets/shares/wb.png
      - assets/shares/wx.png
      - assets/shares/wxpyq.png
      - assets/userbg.jpeg 
      - assets/usbg1.jpg
      - assets/man.png
      - assets/girl.png
      - assets/deheader.jpeg
      - assets/travelBox.jpg
      - assets/login_bg.jpg
      - assets/login_bg2.jpg

      - assets/data/china.json


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
